/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        midnight: "rgb(var(--color-midnight) / <alpha-value>)",
        "navy-deep": "rgb(var(--color-navy-deep) / <alpha-value>)",
        "navy-card": "rgb(var(--color-navy-card) / <alpha-value>)",
        "navy-raise": "rgb(var(--color-navy-raise) / <alpha-value>)",
        "navy-border": "rgb(var(--color-navy-border) / <alpha-value>)",
        white: "rgb(var(--color-text-primary) / <alpha-value>)",
        ash: "rgb(var(--color-text-secondary) / <alpha-value>)",
        fog: "rgb(var(--color-text-muted) / <alpha-value>)",
        amber: "#F59E0B",
        honey: "#FBBF24",
        cream: "#FDE68A",
        ember: "#FF6B5A",
        "ember-dim": "#FF8577",
        success: "#34C97A",
        warning: "#F59E0B",
        danger: "#FF5050",
        info: "#5AC8FA",
      },
      fontFamily: {
        "display": ["Fraunces_900Black"],
        "display-italic": ["Fraunces_900Black_Italic"],
        "body": ["Outfit_400Regular"],
        "body-medium": ["Outfit_500Medium"],
        "body-semibold": ["Outfit_600SemiBold"],
        "body-bold": ["Outfit_700Bold"],
        "body-extrabold": ["Outfit_800ExtraBold"],
        "mono": ["JetBrainsMono_400Regular"],
        "mono-bold": ["JetBrainsMono_700Bold"],
      },
    },
  },
  plugins: [],
};
