export const FORMULA_BRANDS = [
  // Major US brands
  "Similac 360 Total Care",
  "Similac Pro-Advance",
  "Similac Pro-Sensitive",
  "Similac Pro-Total Comfort",
  "Similac Alimentum",
  "Similac Soy Isomil",
  "Similac NeoSure",
  "Similac Special Care",
  "Enfamil NeuroPro",
  "Enfamil NeuroPro Gentlease",
  "Enfamil NeuroPro Sensitive",
  "Enfamil A.R.",
  "Enfamil Reguline",
  "Enfamil Nutramigen",
  "Enfamil ProSobee",
  "Enfamil Enspire",
  "Gerber Good Start GentlePro",
  "Gerber Good Start SoothePro",
  "Gerber Good Start Extensive HA",
  "Gerber Good Start Plant Protein",
  // Store brands
  "Kirkland Signature (Costco)",
  "Member's Mark (Sam's Club)",
  "Parent's Choice (Walmart)",
  "Up & Up (Target)",
  "Comforts (Kroger)",
  "Well Beginnings (Walgreens)",
  // Specialty / organic
  "Earth's Best Organic",
  "Happy Baby Organics",
  "Burt's Bees Baby Organic",
  "Bobbie Organic",
  "Bobbie Organic Gentle",
  "ByHeart",
  "Kendamil",
  "HiPP (imported)",
  "Holle (imported)",
  "Else Plant-Based",
  // Hypoallergenic / medical
  "EleCare",
  "PurAmino",
  "Alfamino",
  "Neocate",
  "Pregestimil",
  // Other
  "Other",
] as const;
